# Generated by Django 4.2.4 on 2023-12-01 15:58

from django.db import migrations, models
import geral.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacoes',
            fields=[
                ('id_doacoes', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('titulo_geral', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=254)),
                ('texto_explicativo', models.TextField()),
                ('image_D', models.ImageField(blank=True, null=True, upload_to=geral.models.upload_media2)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id_publicacao', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=254)),
                ('texto_explicativo', models.TextField()),
                ('valor', models.PositiveIntegerField(default=None, null=True)),
                ('image_P', models.ImageField(blank=True, null=True, upload_to=geral.models.upload_media)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomeUser', models.TextField(max_length=255)),
                ('emailUser', models.EmailField(max_length=255, unique=True)),
                ('senhaUser', models.CharField(max_length=255)),
                ('idadeUser', models.IntegerField()),
            ],
        ),
    ]
