# Generated by Django 4.2.4 on 2023-12-16 18:50

from django.db import migrations, models
import geral.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idadeUser',
        ),
        migrations.AddField(
            model_name='usuario',
            name='image_User',
            field=models.ImageField(blank=True, null=True, upload_to=geral.models.upload_media3),
        ),
        migrations.AlterField(
            model_name='doacoes',
            name='id_doacoes',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='id_publicacao',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
