# Generated by Django 4.2.4 on 2023-12-01 16:09

from django.db import migrations, models
import geral.models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='image_User',
            field=models.ImageField(blank=True, null=True, upload_to=geral.models.upload_media3),
        ),
    ]
