# Generated by Django 4.2.4 on 2023-12-01 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0002_usuario_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacoes',
            name='id_doacoes',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
