# Generated by Django 4.2.4 on 2023-12-01 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0003_alter_doacoes_id_doacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='id_publicacao',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
