# Generated by Django 4.2.4 on 2023-12-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0004_alter_publicacao_id_publicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacao',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idadeUser',
        ),
    ]
